# Generated by Django 4.2.13 on 2024-07-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="account_activated",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="doc_image",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_doc",
        ),
    ]
