# Generated by Django 4.2.13 on 2024-07-29 07:34

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="dept",
                        unique=True,
                    ),
                ),
                ("dept_name", models.CharField(max_length=50, unique=True)),
                ("dept_description", models.CharField()),
                (
                    "dept_image",
                    models.ImageField(blank=True, null=True, upload_to="dept_images/"),
                ),
            ],
        ),
    ]
