# Generated by Django 4.2.13 on 2024-06-18 05:35

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AfterNoonSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.TimeField(unique=True)),
                ("endTime", models.TimeField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="dept",
                        unique=True,
                    ),
                ),
                ("dept_name", models.CharField(max_length=50, unique=True)),
                ("dept_description", models.CharField()),
                (
                    "dept_image",
                    models.ImageField(blank=True, null=True, upload_to="dept_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MorningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.TimeField(unique=True)),
                ("endTime", models.TimeField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="defghijk56789",
                        length=5,
                        max_length=10,
                        prefix="dept",
                        unique=True,
                    ),
                ),
                ("doc_name", models.CharField(max_length=50)),
                (
                    "doc_image",
                    models.ImageField(blank=True, null=True, upload_to="doc_images/"),
                ),
                ("isDeptHead", models.BooleanField(default=False)),
                ("phone", models.CharField(max_length=12, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(default="", null=True)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.department",
                        to_field="dept_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Days",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                (
                    "afternoonSlot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminapp.afternoonslot",
                    ),
                ),
                (
                    "morningSlot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminapp.morningslot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isAvailable", models.BooleanField(default=True)),
                (
                    "day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminapp.days",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminapp.doctors",
                    ),
                ),
            ],
        ),
    ]
