# Generated by Django 4.2.14 on 2024-08-28 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0017_remove_booking_razorpay_order_id_and_more"),
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.IntegerField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Patient Requested", "Patient Requested"),
                            ("Doctor Not Available", "Doctor Not Available"),
                            ("Other", "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "refund",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("No Refund", "No Refund"),
                            ("Refund Requested", "Refund Requested"),
                            ("Refund Completed", "Refund Completed"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
            ],
        ),
    ]
