# Generated by Django 4.2.13 on 2024-06-18 09:40

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="doc_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="defghijk56789",
                length=5,
                max_length=10,
                prefix="doc",
                unique=True,
            ),
        ),
    ]
