# Generated by Django 4.2.14 on 2024-08-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_cancelbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancelbooking",
            name="refund",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Refund", "No Refund"),
                    ("Refund Applicable", "Refund Applicable"),
                    ("Refund Processing", "Refund Processing"),
                    ("Refund Completed", "Refund Completed"),
                ],
                null=True,
            ),
        ),
    ]
