# Generated by Django 4.2.13 on 2024-07-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_alter_doctors_doc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="account_activated",
            field=models.BooleanField(default=False),
        ),
    ]
