# Generated by Django 4.2.14 on 2024-08-10 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "doc_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="doc",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField()),
                ("is_HOD", models.BooleanField(default=False)),
                (
                    "doc_image",
                    models.ImageField(blank=True, null=True, upload_to="doc_images/"),
                ),
                ("account_activated", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.department",
                        to_field="dept_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("message", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="EveningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.TimeField(default=datetime.time(14, 0))),
                ("endTime", models.TimeField(default=datetime.time(18, 0))),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MorningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.TimeField(default=datetime.time(9, 0))),
                ("endTime", models.TimeField(default=datetime.time(13, 0))),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("age", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=3)),
                ("height", models.DecimalField(decimal_places=2, max_digits=3)),
                ("allergies", models.CharField()),
                ("symptoms", models.CharField()),
                ("diagnosis", models.CharField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        blank=True,
                        choices=[("Morning", "Morning"), ("Evening", "Evening")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("isAvailable", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                        to_field="doc_id",
                    ),
                ),
                (
                    "evening",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.eveningslot",
                    ),
                ),
                (
                    "morning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.morningslot",
                    ),
                ),
            ],
            options={
                "unique_together": {("day_of_week", "doctor")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot", models.TimeField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("Direct", "Direct"), ("Razor Pay", "Razor Pay")],
                        max_length=10,
                    ),
                ),
                ("date_of_booking", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.availability",
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "unique_together": {("availability", "time_slot")},
            },
        ),
    ]
