# Generated by Django 4.2.14 on 2024-08-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Female", "Female"), ("Male", "Male"), ("Other", "Other")],
                default="Male",
                null=True,
            ),
        ),
    ]
