# Generated by Django 4.2.14 on 2024-08-14 10:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("200.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
