# Generated by Django 4.2.14 on 2024-08-14 12:17

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctor_fee_patient_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=5,
                max_length=10,
                prefix="pat",
                unique=True,
            ),
        ),
    ]
