# Generated by Django 4.2.14 on 2024-08-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_patient_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="patient",
            field=models.ForeignKey(
                default="patabc123",
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.patient",
                to_field="patient_id",
            ),
            preserve_default=False,
        ),
    ]
