# Generated by Django 4.2.14 on 2024-08-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0006_alter_patient_allergies_alter_patient_diagnosis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
            ),
        ),
    ]
