# Generated by Django 4.2.14 on 2024-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0007_alter_patient_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
