# Generated by Django 4.2.14 on 2024-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0009_remove_patient_doctor_patient_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="doctor",
            field=models.ManyToManyField(blank=True, to="doctors.doctor"),
        ),
    ]
