# Generated by Django 4.2.14 on 2024-08-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0011_alter_booking_patient"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="booking",
            name="booked_day",
            field=models.DateField(default="2024-08-25"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="booking",
            name="availability",
        ),
    ]
