# Generated by Django 4.2.14 on 2024-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0012_alter_booking_unique_together_booking_booked_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
