# Generated by Django 4.2.14 on 2024-08-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0015_alter_booking_doctor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("booked_day", "patient", "doctor")},
        ),
    ]
