# Generated by Django 4.2.14 on 2024-08-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0016_alter_booking_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="razorpay_signature",
        ),
    ]
