# Generated by Django 4.2.14 on 2024-09-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0019_blogs_blogadditionalimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogAdditionalImage",
        ),
        migrations.DeleteModel(
            name="Blogs",
        ),
    ]
